### ISSUE TITLE
UI Header Icons

### ISSUE THREAD

**Issue by atcrme** [cr-crme/defi_photo#11]
Moving the edit Icon (and the save icon) to the left, in order to be aligned with the left side of toggle button on students'pages.
Same for + icon on "Mes élèves" page
![Capture d’écran 2023-01-31 133038](https://user-images.githubusercontent.com/108420242/215868624-196918ea-0a02-4369-b9d8-9988ec3eab5e.png)

**Comment by pariterre** [comment]
Moved it slightly less than asked because it was feeling really weird. Please confirm it is enough!

**Comment by atcrme** [comment]
Works well !
