### ISSUE TITLE
Check icon on question

### ISSUE THREAD

**Issue by atcrme** [cr-crme/defi_photo#16]
On the teacher's screen: 
Moving the check mark icon to the end of a question card, under the "add comment" line.
Adding the label : "Fermer les commentaires" beside the icon
The check mark icon only appears after the student's first answer.
![Capture d’écran 2023-02-06 161035](https://user-images.githubusercontent.com/108420242/217089305-74541654-1605-47a2-94a7-6893aa18e23b.png)

**Comment by pariterre** [comment]
Done
