### ISSUE TITLE
Students'answers pages : Edition vs Read mode

### ISSUE THREAD

**Issue by atcrme** [cr-crme/defi_photo#22]
Increasing the Header's differences between read mode and edition mode on students'answers pages.
Choosing a icon more meaningful

On Edition Mode : 
Changing the Save Icon for a Pencil Off icon 
![image](https://user-images.githubusercontent.com/108420242/217294998-8c7c6192-6f70-485f-ba6f-dc8e97629656.png)
Changing the Page's title from : "Category title" to "Category title : Edition". For example : "Matières et produits : Édition"

![image](https://user-images.githubusercontent.com/108420242/217295700-4fdbdd60-9ae1-4435-8853-54f6ccc71e40.png)
![image](https://user-images.githubusercontent.com/108420242/217295860-406437a6-7323-499d-b860-aadf039e7b45.png)

**Comment by pariterre** [comment]
Done
