### ISSUE TITLE
Student's screen : feedback on teacher's comments

### ISSUE THREAD

**Issue by atcrme** [cr-crme/defi_photo#24]
If a teacher closes a question after adding a comment, there is no feedback on the student's screen that there is a teacher comment on their answer.

Adding a notification on the student's screen for that situation. 
It could be a light blue notification without interrogation mark in it, the size would be the same than the interrogation mark notification

**Comment by pariterre** [comment]
I think I've done it, I suggest you double-check though as I had to change some logic, and therefore may have broken other things (I've done some checks myself... but still..)

Changing the symbol ("?") would be hard and not necessarily helpful. I suggest to keep it like this (I just had some tries and it feels normal to have the "?".
