### ISSUE TITLE
Wording on answers' filters box

### ISSUE THREAD

**Issue by atcrme** [cr-crme/defi_photo#26]
Changing first filter's wording :
Replace : 
"Afficher les réponses de : 
Tous
Élèves uniquement
Enseignant.e uniquement"

By
"Afficher:
Réponses des élèves uniquement
Commentaires de l'enseignant.e uniquement
Ensemble des réponses et commentaires"
By default, "Ensemble des réponses et commentaires" is activated

**Comment by pariterre** [comment]
After trying, I suggest to keep "Ensemble des réponses et commentaires" on top, I don't know why, but it feels weird otherwise
