### ISSUE TITLE
Answers'filters box

### ISSUE THREAD

**Issue by atcrme** [cr-crme/defi_photo#28]
After trying, I suggest reducing the number of fields to avoid scrolling in the window by replacing the radio buttons with checkboxes for the first two filters. 
![InkedfiltreResumeReponses](https://user-images.githubusercontent.com/108420242/221667479-80f19553-f2c3-4bd1-b525-d1bd22d9679c.jpg)

**Comment by pariterre** [comment]
Should we remove "uniquement"?

**Comment by atcrme** [comment]
Yes, good point!

**Comment by pariterre** [comment]
Still relevent?

**Comment by atcrme** [comment]
It is fixed
